### ISSUE TITLE
No AMI for us-east-1-xenial-amd64-hvm-ebs

### ISSUE THREAD

**Issue by backnight** [terraform-community-modules/tf_aws_ubuntu_ami#11]
There is an AMI for us-east-1-trusty-amd64-hvm-ebs but no for us-east-1-xenial-amd64-hvm-ebs.

Is this a bug ?

**Comment by antonbabenko** [comment]
You are right. There is no such AMI provided by Ubuntu - https://cloud-images.ubuntu.com/locator/ec2/
