### ISSUE TITLE
Not compatible with Terraform 0.7.0

### ISSUE THREAD

**Issue by kbruner** [terraform-community-modules/tf_aws_ubuntu_ami#8]
It looks like the change to `lookup` breaks the `ami_id` output here:

```
output "ami_id" {
    value = "${lookup(var.all_amis, format(\"%s-%s-%s-%s-%s\", var.region, var.distribution, var.architecture, var.virttype, var.storagetype))}"
}
```

**Comment by antonbabenko** [comment]
This has already been fixed in https://github.com/terraform-community-modules/tf_aws_ubuntu_ami/pull/7

**Comment by kbruner** [comment]
Oh, strange, `terraform get` was erroring out on this module.  I had to delete my `.terraform/modules` directory to update, and after that it was fine.  Sorry about that.
